[display]
compact = false
use_pager = true
show_title = true

[updates]
auto_update = true
auto_update_interval_hours = 168

[style.command_name]
foreground = "blue"
bold = true

[style.example_text]
foreground = "white"

[style.example_code]
foreground = "green"

[style.example_variable]
foreground = "yellow"
underline = true
