setenv XDG_CURRENT_DESKTOP sway
setenv XDG_SESSION_DESKTOP sway
setenv XDG_SESSION_TYPE wayland

setenv MOZ_ENABLE_WAYLAND 1
setenv QT_QPA_PLATFORM wayland;xcb
setenv QT_WAYLAND_DISABLE_WINDOWDECORATION 1
setenv SDL_VIDEODRIVER wayland
setenv CLUTTER_BACKEND wayland
setenv _JAVA_AWT_WM_NONREPARENTING 1
